### PR TITLE
Improve warnings of bucklescript compiler

### PR DESCRIPTION
**Pull request by hamza0867**
This PR aims to provide improved bucklescript error messages working out of the box

### CODE REVIEW

**Comment by tatchi** [comment]
Thanks for the PR @hamza0867. I think that these options are more of personal preferences, other people might prefer another set of rules.

So I would personally prefer not to take any opinion on this and let people adjust it to their preferences. Also, the official [react-hooks template](https://reasonml.github.io/reason-react/docs/en/installation#using-bucklescript-init) does not modify these warnings/errors options and I think that staying as close as possible to this official template would be better.

What do you think?

**Comment by hamza0867** [comment]
Ok how about this ? we leave it in the template commented out with a comment saying that this warnings section enables stricter compilation mode like failing on non exhaustive pattern matches which leads to fewer runtime bugs.

**Comment by tatchi** [comment]
> Ok how about this ? we leave it in the template commented out with a comment saying that this warnings section enables stricter compilation mode like failing on non exhaustive pattern matches which leads to fewer runtime bugs.

Sounds a good compromise 👍Feel free also to point to yawaramin's post to give more explanation if you think that might be relevant :)

**Comment by hamza0867** [comment]
Cool I just commented out that warnings section with a link to yawaramin's post. Please tell me what you think. :)

**Review by tatchi — APPROVED** [review]

**Pull request merged**
