### PR TITLE
Svelte app templates

### PR DESCRIPTION
**Pull request by codechips**
Add two simplest possible Svelte app templates: JS only and Typescript

### CODE REVIEW

**Comment by yyx990803** [comment]
Looks like `vite-plugin-svelte` hasn't been updated for a while, @intrnl are you still planning to maintain it?

For using Svelte with Vite it's probably better to use [svite](https://github.com/dominikg/svite) (which is built on top of Vite)

**Comment by intrnl** [comment]
I still maintain the plugin, but I'd recommend Svite over mine, since it's much better fleshed out (reads svelte.config.js and all that)

**Comment by codechips** [comment]
I also tend to use Svite more and more.

**Comment by yyx990803** [comment]
Closing this then, so that we don't have to always keep this one up to date.

**Pull request closed without merging**
